# Use an official Python 3.10 runtime on Alpine Linux as a parent image
FROM python:3.10-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the application files and data into the container
COPY scripts/ /app
COPY data/ /app/data

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Run the test application
CMD ["pytest","-s","/app/test_app.py"]